type Query {
    """
    This is just a test schema
    """
    test:Boolean
}
type User{
    id:String!
    email:String!
    name:String!
}
type Token {
    token:String
}
type Login {
    User:User,
    Token:Token
}

type Mutation{
    """
    Login user
    """
    login(email:String!,password:String!):Login
}